"use client";

import { use } from "react";
import Link from "next/link";
import { ArrowLeft, BookOpen, Clock, Heart } from "lucide-react";

interface HelpArticlePageProps {
  params: Promise<{ articleSlug: string }>;
}

const MOCK_ARTICLES: Record<string, { title: string; category: string; body: string }> = {
  "access-classroom": {
    title: "How to access enrolled program classrooms",
    category: "Learner Support",
    body: "Once you purchase a course program or subscribe to an Academy Pass plan, you can access the classroom by logging in and navigating to your Student Dashboard. Under the 'Continue Learning' section, click 'Go to Classroom' or 'Watch'. If a lesson appears locked, verify that your monthly billing pass is currently active under the Memberships tab.",
  },
  "verify-certificate": {
    title: "Retrieving and verifying certificates",
    category: "Learner Support",
    body: "Upon completing all video lectures and required worksheets, a certificate is auto-generated by the platform registrar. Navigate to your Student Dashboard and click on the 'Certificates' tab to view or print the document. Each credential includes a unique ledger verification ID that external employers can lookup directly under the verify portal (e.g. /verify/certId).",
  },
  "ai-copilot-guide": {
    title: "Generating quizzes and lessons using AI Copilot",
    category: "Academy Studio Operations",
    body: "Inside the Creator Dashboard, navigate to the 'AI Copilot' section. Here, you can type natural language instructions such as 'Create a 5-question beginner Python decorators quiz' or 'Gen syllabus structure for react design systems'. The copilot workspace will generate draft lessons, outlines, or assessments that you can directly append to your curriculum editor.",
  }
};

export default function HelpArticlePage({ params }: HelpArticlePageProps) {
  const { articleSlug } = use(params);

  const article = MOCK_ARTICLES[articleSlug] || {
    title: "Support documentation article",
    category: "General Support",
    body: "This support documentation outlines the core operational behaviors of the LearnioX edtech registry. For further instructions, please contact our support desk.",
  };

  return (
    <div className="max-w-[800px] mx-auto px-6 py-12 space-y-8 font-sans">
      {/* Back button */}
      <div>
        <Link
          href="/help"
          className="inline-flex items-center gap-2 text-label-sm uppercase tracking-wider text-muted-foreground hover:text-foreground transition-colors font-bold"
        >
          <ArrowLeft className="w-4 h-4" /> Help Center
        </Link>
      </div>

      {/* Article Content */}
      <article className="border border-border bg-card p-6 md:p-8 space-y-6">
        <div className="space-y-2">
          <span className="text-[10px] text-muted-foreground uppercase font-bold tracking-widest bg-surface-container border border-border px-3 py-1">
            {article.category}
          </span>
          <h1 className="text-headline-md md:text-headline-lg font-bold text-foreground pt-2">
            {article.title}
          </h1>
          <div className="flex gap-4 text-xs text-muted-foreground pt-1 font-mono">
            <span className="flex items-center gap-1"><Clock className="w-3.5 h-3.5" /> 3 min read</span>
            <span className="flex items-center gap-1"><BookOpen className="w-3.5 h-3.5" /> Updated recently</span>
          </div>
        </div>

        <div className="text-body-md text-muted-foreground leading-relaxed whitespace-pre-wrap pt-4 border-t border-border">
          {article.body}
        </div>
      </article>

      {/* Helpful CTA */}
      <div className="border border-border p-4 text-center space-y-3 bg-surface">
        <p className="text-xs uppercase tracking-wider text-muted-foreground font-bold">Was this article helpful?</p>
        <div className="flex justify-center gap-4">
          <button className="px-4 py-2 border border-border bg-card text-xs uppercase tracking-widest font-bold hover:bg-surface-container transition-colors inline-flex items-center gap-1.5">
            <Heart className="w-3.5 h-3.5 text-rose-600" /> Yes
          </button>
          <button className="px-4 py-2 border border-border bg-card text-xs uppercase tracking-widest font-bold hover:bg-surface-container transition-colors">
            No
          </button>
        </div>
      </div>
    </div>
  );
}
