import enum


class AssessmentType(str, enum.Enum):
    """
    14 Creator-Selectable Assessment Types supported in LearnioX.
    """
    MCQ = "MCQ"
    TRUE_FALSE = "TRUE_FALSE"
    MULTIPLE_SELECT = "MULTIPLE_SELECT"
    FILL_IN_BLANK = "FILL_IN_BLANK"
    SHORT_ANSWER = "SHORT_ANSWER"
    LONG_ANSWER_ESSAY = "LONG_ANSWER_ESSAY"
    CODING_QUESTION = "CODING_QUESTION"
    FILE_UPLOAD_ASSIGNMENT = "FILE_UPLOAD_ASSIGNMENT"
    MATCHING = "MATCHING"
    ORDERING = "ORDERING"
    CASE_STUDY = "CASE_STUDY"
    PROJECT = "PROJECT"
    PRACTICAL_LAB = "PRACTICAL_LAB"
    COURSE_FINAL_EXAM = "COURSE_FINAL_EXAM"
