import json
import logging
from typing import Any, Dict, Optional
from app.providers.base import BaseLLMProvider, BaseTranscriptionProvider

logger = logging.getLogger("learniox.ai.providers.mock")


class MockLLMProvider(BaseLLMProvider):
    """
    Offline deterministic Mock LLM provider for development and automated testing
    when no cloud LLM API key (GEMINI_API_KEY) is supplied.
    """

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def is_configured(self) -> bool:
        return True

    async def generate_text(
        self,
        prompt: str,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        logger.info("MockLLMProvider: generating simulated text response.")
        return (
            "This is a simulated AI response generated by LearnioX MockLLMProvider "
            "for local development and zero-dependency offline testing."
        )

    async def generate_json(
        self,
        prompt: str,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> Dict[str, Any]:
        logger.info("MockLLMProvider: generating simulated JSON response.")
        # Minimal mock JSON that conforms to assessment/tutor responses
        return {
            "mock": True,
            "provider": "mock",
            "message": "Simulated structured response",
            "items": [],
        }


class MockTranscriptionProvider(BaseTranscriptionProvider):
    """
    Offline deterministic Mock Speech-to-Text provider.
    Generates realistic timestamped segments for testing HTML5 player sync.
    """

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def is_configured(self) -> bool:
        return True

    async def transcribe_audio(
        self,
        file_path: str,
        language: Optional[str] = "en",
    ) -> Dict[str, Any]:
        logger.info(f"MockTranscriptionProvider: generating mock transcript for {file_path}")
        segments = [
            {
                "id": 0,
                "start": 0.0,
                "end": 8.5,
                "text": "Welcome to LearnioX. In this lecture, we explore the foundational concepts of our curriculum.",
            },
            {
                "id": 1,
                "start": 8.5,
                "end": 22.0,
                "text": "First, let us examine the fundamental architecture and design patterns required for scalable systems.",
            },
            {
                "id": 2,
                "start": 22.0,
                "end": 39.5,
                "text": "Notice how decoupling state and persistence leads to significantly improved testability and maintainability.",
            },
            {
                "id": 3,
                "start": 39.5,
                "end": 58.0,
                "text": "Finally, we will put this into practice by writing clean, modular code following domain-driven design principles.",
            },
        ]
        full_text = " ".join(s["text"] for s in segments)
        return {
            "text": full_text,
            "language": language or "en",
            "duration": 60.0,
            "segments": segments,
        }
