import type { Course, Category, CourseReview } from "@/types/course";

export const MOCK_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Computer Science & Engineering", slug: "computer-science", courseCount: 1240, order: 1, icon: "code" },
  { id: "cat-2", name: "Business Administration", slug: "business", courseCount: 850, order: 2, icon: "briefcase" },
  { id: "cat-3", name: "Data Analytics & AI", slug: "data-analytics", courseCount: 620, order: 3, icon: "bar-chart" },
  { id: "cat-4", name: "Design & UX", slug: "design", courseCount: 480, order: 4, icon: "palette" },
  { id: "cat-5", name: "Government Exams (UPSC/SSC)", slug: "government-exams", courseCount: 960, order: 5, icon: "landmark" },
  { id: "cat-6", name: "JEE / NEET Preparation", slug: "jee-neet", courseCount: 1100, order: 6, icon: "flask" },
  { id: "cat-7", name: "Spoken English", slug: "spoken-english", courseCount: 340, order: 7, icon: "mic" },
  { id: "cat-8", name: "Finance & Accounting", slug: "finance", courseCount: 520, order: 8, icon: "indian-rupee" },
];

export const MOCK_COURSES: Course[] = [
  {
    id: "course-1",
    slug: "advanced-python-data-science",
    title: "Advanced Python for Data Science",
    description: "Master Python for data science with pandas, numpy, scikit-learn, and deep learning frameworks. Build real-world ML pipelines.",
    shortDescription: "End-to-end Python for ML/AI with real projects and industry workflows.",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80",
    institutionId: "inst-1",
    institutionName: "TechGlobal Institute",
    institutionSlug: "techglobal",
    instructorIds: ["user-instructor-1"],
    instructors: [{ id: "user-instructor-1", name: "Dr. Ankit Sharma", title: "Senior ML Engineer", avatar: undefined }],
    categoryId: "cat-1",
    categoryName: "Computer Science & Engineering",
    tags: ["python", "machine learning", "data science", "ai"],
    level: "advanced",
    pricingType: "paid",
    price: 4999,
    originalPrice: 9999,
    currency: "INR",
    visibility: "public",
    language: "English",
    totalLessons: 142,
    totalDuration: 432000, // 120 hours
    totalModules: 12,
    enrollmentCount: 15302,
    rating: 4.9,
    reviewCount: 2841,
    completionRate: 68,
    certificate: true,
    requirements: ["Basic Python knowledge", "High school math"],
    outcomes: ["Build ML models", "Deploy AI applications", "Work with real datasets"],
    targetAudience: ["Software developers", "Data analysts", "Students"],
    modules: [
      {
        id: "mod-1",
        courseId: "course-1",
        title: "Module 1: Advanced Python Core Concepts",
        description: "Deep dive into memory management, generators, decorators, and OOP.",
        order: 1,
        isPreview: true,
        totalDuration: 7200,
        lessons: [
          {
            id: "lesson-1",
            moduleId: "mod-1",
            title: "1.1 Introduction to Advanced Python",
            description: "An overview of what we will cover in this course and why Python memory model matters.",
            type: "video",
            duration: 900,
            order: 1,
            isPreview: true,
            isLocked: false,
            videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4"
          },
          {
            id: "lesson-2",
            moduleId: "mod-1",
            title: "1.2 Python Memory Management & GC",
            description: "How reference counting and garbage collection work in CPython.",
            type: "video",
            duration: 1800,
            order: 2,
            isPreview: true,
            isLocked: false,
            videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4"
          },
          {
            id: "lesson-3",
            moduleId: "mod-1",
            title: "1.3 Decorators and Metaprogramming",
            description: "Write custom decorators with arguments and understand type metaclasses.",
            type: "video",
            duration: 2100,
            order: 3,
            isPreview: false,
            isLocked: false,
            videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4"
          },
          {
            id: "lesson-4",
            moduleId: "mod-1",
            title: "1.4 Quiz: Python Core Internals",
            description: "Test your understanding of python decorators and memory management.",
            type: "quiz",
            order: 4,
            isPreview: false,
            isLocked: false,
            quizId: "quiz-python-1"
          }
        ]
      },
      {
        id: "mod-2",
        courseId: "course-1",
        title: "Module 2: Advanced NumPy & Pandas",
        description: "Vectorization, broadcasting rules, and high-performance dataframe operations.",
        order: 2,
        isPreview: false,
        totalDuration: 10800,
        lessons: [
          {
            id: "lesson-5",
            moduleId: "mod-2",
            title: "2.1 Vectorized Computations in NumPy",
            description: "Avoid loops and use vectorization for 100x speedups.",
            type: "video",
            duration: 2400,
            order: 1,
            isPreview: false,
            isLocked: false,
            videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4"
          },
          {
            id: "lesson-6",
            moduleId: "mod-2",
            title: "2.2 Advanced Pandas GroupBy and Merge",
            description: "Complex splits, apply functions, and optimized merging.",
            type: "video",
            duration: 3000,
            order: 2,
            isPreview: false,
            isLocked: false,
            videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4"
          },
          {
            id: "lesson-7",
            moduleId: "mod-2",
            title: "Assignment: Optimization Project",
            description: "Take a slow python loop script and optimize it using NumPy vectorization.",
            type: "assignment",
            order: 3,
            isPreview: false,
            isLocked: false,
            assignmentId: "assign-python-1"
          }
        ]
      }
    ],
    isPublished: true,
    publishedAt: "2024-01-15T00:00:00Z",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
    isBestseller: true,
    isFeatured: true,
  },
  {
    id: "course-2",
    slug: "enterprise-software-architecture",
    title: "Enterprise Software Architecture Integration",
    description: "Learn to design scalable, resilient enterprise architectures. Covers microservices, event-driven design, and system patterns.",
    shortDescription: "Design systems that scale from 1K to 10M users.",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    institutionId: "inst-2",
    institutionName: "TechGlobal Institute",
    institutionSlug: "techglobal",
    instructorIds: ["user-instructor-2"],
    instructors: [{ id: "user-instructor-2", name: "Priya Mehta", title: "Principal Architect", avatar: undefined }],
    categoryId: "cat-1",
    categoryName: "Computer Science & Engineering",
    tags: ["architecture", "microservices", "system design"],
    level: "intermediate",
    pricingType: "paid",
    price: 7999,
    originalPrice: 14999,
    currency: "INR",
    visibility: "public",
    language: "English",
    totalLessons: 98,
    totalDuration: 288000,
    totalModules: 10,
    enrollmentCount: 4210,
    rating: 4.9,
    reviewCount: 856,
    completionRate: 71,
    certificate: true,
    requirements: ["3+ years development experience", "Basic distributed systems knowledge"],
    outcomes: ["Design scalable systems", "Implement microservices", "Lead architecture reviews"],
    targetAudience: ["Senior developers", "Tech leads", "Architects"],
    modules: [],
    isPublished: true,
    publishedAt: "2024-02-01T00:00:00Z",
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-05-10T00:00:00Z",
  },
  {
    id: "course-3",
    slug: "design-systems-react",
    title: "Design Systems in React",
    description: "Build comprehensive design systems using React, TypeScript, and Storybook. Learn component architecture, theming, and documentation.",
    shortDescription: "Build scalable UI component libraries from scratch.",
    thumbnail: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&q=80",
    institutionId: "inst-3",
    institutionName: "Design Institute",
    institutionSlug: "design-institute",
    instructorIds: ["user-instructor-3"],
    instructors: [{ id: "user-instructor-3", name: "Ritu Kapoor", title: "Lead UI Engineer", avatar: undefined }],
    categoryId: "cat-4",
    categoryName: "Design & UX",
    tags: ["react", "design systems", "typescript", "storybook"],
    level: "intermediate",
    pricingType: "paid",
    price: 3999,
    originalPrice: 7999,
    currency: "INR",
    visibility: "public",
    language: "English",
    totalLessons: 76,
    totalDuration: 216000,
    totalModules: 8,
    enrollmentCount: 3850,
    rating: 4.8,
    reviewCount: 624,
    completionRate: 75,
    certificate: true,
    requirements: ["React basics", "HTML/CSS proficiency"],
    outcomes: ["Build component libraries", "Implement design tokens", "Write component tests"],
    targetAudience: ["Frontend developers", "UI engineers", "Designers who code"],
    modules: [],
    isPublished: true,
    publishedAt: "2024-03-01T00:00:00Z",
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "course-4",
    slug: "foundations-structural-ui-design",
    title: "Foundations of Structural UI Design",
    description: "Learn the fundamentals of structural, functional UI design. Covers layout theory, typography, color systems, and accessibility.",
    shortDescription: "Master the fundamentals of professional UI design.",
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80",
    institutionId: "inst-3",
    institutionName: "Design Institute",
    institutionSlug: "design-institute",
    instructorIds: ["user-instructor-3"],
    instructors: [{ id: "user-instructor-3", name: "Ritu Kapoor", title: "Lead UI Engineer", avatar: undefined }],
    categoryId: "cat-4",
    categoryName: "Design & UX",
    tags: ["ui design", "layout", "typography", "accessibility"],
    level: "beginner",
    pricingType: "free",
    currency: "INR",
    visibility: "public",
    language: "English",
    totalLessons: 45,
    totalDuration: 108000,
    totalModules: 6,
    enrollmentCount: 8920,
    rating: 4.7,
    reviewCount: 1240,
    completionRate: 82,
    certificate: false,
    requirements: [],
    outcomes: ["Understand UI fundamentals", "Create effective layouts", "Apply typography rules"],
    targetAudience: ["Beginners", "Developers learning design", "Product managers"],
    modules: [],
    isPublished: true,
    publishedAt: "2024-01-10T00:00:00Z",
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-04-20T00:00:00Z",
    isFeatured: true,
  },
  {
    id: "course-5",
    slug: "machine-learning-operations-mlops",
    title: "Machine Learning Operations (MLOps)",
    description: "Learn to deploy, monitor, and maintain ML models in production. Covers CI/CD for ML, model versioning, drift detection.",
    shortDescription: "Take your ML models from notebook to production.",
    thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    institutionId: "inst-4",
    institutionName: "DataSys Academy",
    institutionSlug: "datasys",
    instructorIds: ["user-instructor-4"],
    instructors: [{ id: "user-instructor-4", name: "Rahul Gupta", title: "MLOps Engineer", avatar: undefined }],
    categoryId: "cat-3",
    categoryName: "Data Analytics & AI",
    tags: ["mlops", "devops", "machine learning", "deployment"],
    level: "advanced",
    pricingType: "paid",
    price: 5999,
    originalPrice: 11999,
    currency: "INR",
    visibility: "public",
    language: "English",
    totalLessons: 88,
    totalDuration: 259200,
    totalModules: 9,
    enrollmentCount: 2100,
    rating: 4.8,
    reviewCount: 389,
    completionRate: 58,
    certificate: true,
    requirements: ["ML fundamentals", "Python", "Docker basics"],
    outcomes: ["Deploy ML models", "Build ML pipelines", "Monitor model performance"],
    targetAudience: ["ML engineers", "Data scientists", "DevOps engineers"],
    modules: [],
    isPublished: true,
    publishedAt: "2024-04-01T00:00:00Z",
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-05-20T00:00:00Z",
  },
  {
    id: "course-6",
    slug: "zero-trust-network-architecture",
    title: "Zero Trust Network Architecture",
    description: "Implement Zero Trust security models for modern enterprise environments. Covers identity, access management, and micro-segmentation.",
    shortDescription: "Secure enterprise networks with Zero Trust principles.",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
    institutionId: "inst-5",
    institutionName: "CyberSec Institute",
    institutionSlug: "cybersec",
    instructorIds: ["user-instructor-5"],
    instructors: [{ id: "user-instructor-5", name: "Vikram Singh", title: "CISO", avatar: undefined }],
    categoryId: "cat-1",
    categoryName: "Computer Science & Engineering",
    tags: ["security", "zero trust", "networking", "cybersecurity"],
    level: "expert",
    pricingType: "paid",
    price: 8999,
    originalPrice: 17999,
    currency: "INR",
    visibility: "public",
    language: "English",
    totalLessons: 120,
    totalDuration: 345600,
    totalModules: 14,
    enrollmentCount: 1540,
    rating: 4.9,
    reviewCount: 298,
    completionRate: 62,
    certificate: true,
    requirements: ["Network fundamentals", "5+ years IT experience"],
    outcomes: ["Design Zero Trust architectures", "Implement IAM policies", "Conduct security audits"],
    targetAudience: ["Security professionals", "Network engineers", "CISOs"],
    modules: [],
    isPublished: true,
    publishedAt: "2024-02-15T00:00:00Z",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-05-05T00:00:00Z",
  },
];

export const MOCK_FEATURED_COURSES = MOCK_COURSES.filter((c) => c.isFeatured || c.isBestseller);
export const MOCK_FREE_COURSES = MOCK_COURSES.filter((c) => c.pricingType === "free");

export const MOCK_COURSE_REVIEWS: CourseReview[] = [
  {
    id: "review-1",
    courseId: "course-1",
    userId: "user-learner-1",
    userName: "Arjun Patel",
    rating: 5,
    comment: "Absolutely brilliant course. The progression from basics to production ML is seamless. Best investment I've made in my career.",
    createdAt: "2024-05-01T00:00:00Z",
    isVerified: true,
    helpfulCount: 124,
  },
  {
    id: "review-2",
    courseId: "course-1",
    userId: "user-learner-2",
    userName: "Sneha Reddy",
    rating: 5,
    comment: "The real-world projects made all the difference. I landed a data scientist role within 2 months of completing this course.",
    createdAt: "2024-04-15T00:00:00Z",
    isVerified: true,
    helpfulCount: 98,
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return MOCK_COURSES.find((c) => c.slug === slug);
}

export function getCoursesByInstitution(institutionId: string): Course[] {
  return MOCK_COURSES.filter((c) => c.institutionId === institutionId);
}

export function getCoursesByCategory(categoryId: string): Course[] {
  return MOCK_COURSES.filter((c) => c.categoryId === categoryId);
}
