import type { Institution, InstitutionMember, InstitutionMembership } from "@/types/institution";

export const MOCK_INSTITUTIONS: Institution[] = [
  {
    id: "inst-1",
    slug: "techglobal",
    name: "TechGlobal Institute",
    tagline: "Industry-first technical education for the modern engineer",
    description: "TechGlobal is India's leading technical education platform, with over 15 years of experience training software engineers, data scientists, and architects. Our curriculum is co-designed with top technology companies.",
    logo: undefined,
    banner: undefined,
    categories: ["Computer Science & Engineering", "Data Analytics & AI"],
    tags: ["coding", "tech", "engineering", "AI"],
    status: "active",
    isVerified: true,
    plan: "pro",
    ownerId: "user-owner-1",
    ownerName: "Ramesh Iyer",
    memberCount: 24,
    studentCount: 45200,
    courseCount: 18,
    rating: 4.8,
    reviewCount: 5840,
    followersCount: 128000,
    socialLinks: {
      website: "https://techglobal.edu.in",
      twitter: "techglobal_edu",
      youtube: "TechGlobalInstitute",
    },
    contactEmail: "hello@techglobal.edu.in",
    foundedYear: 2009,
    achievements: ["Best EdTech Platform 2023", "50K+ Alumni", "Google Certified Partner"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
    isFeatured: true,
    institutionType: "edtech_startup",
  },
  {
    id: "inst-2",
    slug: "quantumlogic",
    name: "Quantum Logic Academy",
    tagline: "Engineering excellence through structured learning",
    description: "Quantum Logic specializes in advanced computer science, system design, and enterprise architecture. We train engineers to think at scale.",
    logo: undefined,
    banner: undefined,
    categories: ["Computer Science & Engineering"],
    tags: ["system design", "architecture", "advanced coding"],
    status: "active",
    isVerified: true,
    plan: "business",
    ownerId: "user-owner-2",
    ownerName: "Deepak Joshi",
    memberCount: 12,
    studentCount: 18400,
    courseCount: 9,
    rating: 4.9,
    reviewCount: 2100,
    followersCount: 52000,
    socialLinks: { website: "https://quantumlogic.in" },
    contactEmail: "info@quantumlogic.in",
    foundedYear: 2016,
    achievements: ["Top System Design Course 2023", "18K+ Engineers Trained"],
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-04-20T00:00:00Z",
    institutionType: "corporate_training",
  },
  {
    id: "inst-3",
    slug: "design-institute",
    name: "Design Institute",
    tagline: "Building tomorrow's design leaders",
    description: "Design Institute offers world-class education in UI/UX, product design, and design systems. Our graduates work at top product companies globally.",
    logo: undefined,
    banner: undefined,
    categories: ["Design & UX"],
    tags: ["ui", "ux", "product design", "figma"],
    status: "active",
    isVerified: true,
    plan: "pro",
    ownerId: "user-owner-3",
    ownerName: "Ritu Kapoor",
    memberCount: 8,
    studentCount: 22100,
    courseCount: 12,
    rating: 4.8,
    reviewCount: 3200,
    followersCount: 78000,
    socialLinks: { website: "https://designinstitute.in", instagram: "designinstitute_in" },
    contactEmail: "studio@designinstitute.in",
    foundedYear: 2018,
    achievements: ["Best Design School 2022", "22K+ Designers Trained"],
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-05-10T00:00:00Z",
    isFeatured: true,
    institutionType: "college_university",
  },
  {
    id: "inst-4",
    slug: "datasys",
    name: "DataSys Academy",
    tagline: "From raw data to real decisions",
    description: "DataSys Academy focuses on data engineering, analytics, and AI operations. Practical, industry-aligned curriculum with guaranteed placement support.",
    logo: undefined,
    banner: undefined,
    categories: ["Data Analytics & AI"],
    tags: ["data", "analytics", "mlops", "sql"],
    status: "active",
    isVerified: false,
    plan: "starter",
    ownerId: "user-owner-4",
    ownerName: "Rahul Gupta",
    memberCount: 5,
    studentCount: 8900,
    courseCount: 6,
    rating: 4.7,
    reviewCount: 980,
    followersCount: 24000,
    socialLinks: { website: "https://datasys.academy" },
    contactEmail: "hello@datasys.academy",
    foundedYear: 2021,
    achievements: ["Fastest Growing EdTech 2023"],
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
    institutionType: "k12_school",
  },
  {
    id: "inst-5",
    slug: "cybersec",
    name: "CyberSec Institute",
    tagline: "Securing the digital world, one engineer at a time",
    description: "CyberSec Institute is India's premier cybersecurity education platform. Our instructors are active security professionals with government and enterprise experience.",
    logo: undefined,
    banner: undefined,
    categories: ["Computer Science & Engineering"],
    tags: ["security", "networking", "ethical hacking", "compliance"],
    status: "active",
    isVerified: true,
    plan: "pro",
    ownerId: "user-owner-5",
    ownerName: "Vikram Singh",
    memberCount: 10,
    studentCount: 12800,
    courseCount: 8,
    rating: 4.9,
    reviewCount: 1560,
    followersCount: 38000,
    socialLinks: { website: "https://cybersec.institute" },
    contactEmail: "secure@cybersec.institute",
    foundedYear: 2015,
    achievements: ["CEH Partner Institute", "Government Certified Programs"],
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
    institutionType: "workshop_seminar",
  },
];

export const MOCK_INSTITUTION_MEMBERS: InstitutionMember[] = [
  {
    id: "member-1",
    institutionId: "inst-3",
    userId: "user-owner-3",
    name: "Ritu Kapoor",
    email: "ritu@designinstitute.in",
    role: "owner",
    permissions: ["courses.create", "courses.edit", "courses.delete", "courses.publish", "students.view", "students.manage", "doubts.view", "doubts.answer", "analytics.view", "payments.view", "payments.manage", "team.manage", "settings.manage", "ai.use"],
    joinedAt: "2024-02-01T00:00:00Z",
    lastActiveAt: "2024-05-28T10:00:00Z",
    status: "active",
  },
  {
    id: "member-2",
    institutionId: "inst-3",
    userId: "user-instructor-3",
    name: "Ananya Verma",
    email: "ananya@designinstitute.in",
    role: "lead_instructor",
    permissions: ["courses.create", "courses.edit", "doubts.view", "doubts.answer", "students.view"],
    joinedAt: "2024-03-01T00:00:00Z",
    lastActiveAt: "2024-05-27T14:00:00Z",
    status: "active",
  },
  {
    id: "member-3",
    institutionId: "inst-3",
    userId: "user-support-1",
    name: "Kiran Raj",
    email: "kiran@designinstitute.in",
    role: "support_agent",
    permissions: ["doubts.view", "doubts.answer", "students.view"],
    joinedAt: "2024-04-01T00:00:00Z",
    status: "active",
  },
];

export const MOCK_MEMBERSHIPS: InstitutionMembership[] = [
  {
    id: "membership-1",
    institutionId: "inst-3",
    name: "Design Starter",
    description: "Access to all beginner courses and community forums.",
    price: 499,
    billingCycle: "monthly",
    features: ["5 beginner courses", "Community access", "Monthly live Q&A", "Certificate on completion"],
    courseAccess: "selected",
    isActive: true,
    createdAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "membership-2",
    institutionId: "inst-3",
    name: "Design Pro",
    description: "Full access to all courses, weekly live sessions, and doubt resolution.",
    price: 999,
    billingCycle: "monthly",
    features: ["All courses", "Weekly live sessions", "Priority doubt resolution", "Project reviews", "Certificates", "Community access", "Recording downloads"],
    courseAccess: "all",
    isPopular: true,
    isActive: true,
    createdAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "membership-3",
    institutionId: "inst-3",
    name: "Design Elite",
    description: "Everything in Pro plus 1:1 mentorship, portfolio review, and placement support.",
    price: 2499,
    billingCycle: "monthly",
    features: ["Everything in Pro", "1:1 mentorship (2 sessions/month)", "Portfolio review", "Placement support", "Interview prep", "LinkedIn optimization"],
    courseAccess: "all",
    isActive: true,
    createdAt: "2024-02-01T00:00:00Z",
  },
];

export function getInstitutionBySlug(slug: string): Institution | undefined {
  return MOCK_INSTITUTIONS.find((i) => i.slug === slug);
}

export function getFeaturedInstitutions(): Institution[] {
  return MOCK_INSTITUTIONS.filter((i) => i.isFeatured);
}
