import type { Enrollment, Note, Doubt, Certificate, MembershipSubscription, Payment, AssignmentSubmission } from "@/types/enrollment";

export const MOCK_ENROLLMENTS: Enrollment[] = [
  {
    id: "enroll-1",
    courseId: "course-1",
    courseTitle: "Advanced Python for Data Science",
    courseThumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&q=80",
    institutionId: "inst-1",
    institutionName: "TechGlobal Institute",
    userId: "user-learner-1",
    enrolledAt: "2024-03-01T00:00:00Z",
    accessType: "purchased",
    progress: {
      enrollmentId: "enroll-1",
      courseId: "course-1",
      completionPercentage: 65,
      completedLessons: [],
      totalLessons: 142,
      watchTimeSeconds: 234000,
      lastLessonId: "lesson-12",
      lastLessonTitle: "1.2 Memory Management",
    },
    lastAccessedAt: "2024-05-27T18:00:00Z",
  },
  {
    id: "enroll-2",
    courseId: "course-2",
    courseTitle: "Enterprise Software Architecture Integration",
    courseThumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80",
    institutionId: "inst-2",
    institutionName: "Quantum Logic Academy",
    userId: "user-learner-1",
    enrolledAt: "2024-04-15T00:00:00Z",
    accessType: "purchased",
    progress: {
      enrollmentId: "enroll-2",
      courseId: "course-2",
      completionPercentage: 0,
      completedLessons: [],
      totalLessons: 98,
      watchTimeSeconds: 0,
    },
    lastAccessedAt: "2024-04-16T10:00:00Z",
  },
  {
    id: "enroll-3",
    courseId: "course-6",
    courseTitle: "Zero Trust Network Architecture",
    courseThumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&q=80",
    institutionId: "inst-5",
    institutionName: "CyberSec Institute",
    userId: "user-learner-1",
    enrolledAt: "2024-02-01T00:00:00Z",
    accessType: "purchased",
    progress: {
      enrollmentId: "enroll-3",
      courseId: "course-6",
      completionPercentage: 45,
      completedLessons: [],
      totalLessons: 120,
      watchTimeSeconds: 155520,
    },
    lastAccessedAt: "2024-05-25T20:00:00Z",
  },
  {
    id: "enroll-4",
    courseId: "course-3",
    courseTitle: "Design Systems in React",
    courseThumbnail: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=400&q=80",
    institutionId: "inst-3",
    institutionName: "Design Institute",
    userId: "user-learner-1",
    enrolledAt: "2024-01-15T00:00:00Z",
    accessType: "membership",
    progress: {
      enrollmentId: "enroll-4",
      courseId: "course-3",
      completionPercentage: 89,
      completedLessons: [],
      totalLessons: 76,
      watchTimeSeconds: 189000,
    },
    lastAccessedAt: "2024-05-28T08:00:00Z",
  },
];

export const MOCK_NOTES: Note[] = [
  {
    id: "note-1",
    userId: "user-learner-1",
    courseId: "course-1",
    courseTitle: "Advanced Python for Data Science",
    lessonId: "lesson-12",
    lessonTitle: "Memory Management",
    content: "Review binary tree inversion logic for upcoming technical screen. Need to optimize space complexity. Key insight: use recursion with O(h) space where h is tree height.",
    timestamp: 1240,
    createdAt: "2024-05-26T14:00:00Z",
    updatedAt: "2024-05-26T14:00:00Z",
  },
  {
    id: "note-2",
    userId: "user-learner-1",
    courseId: "course-1",
    courseTitle: "Advanced Python for Data Science",
    lessonId: "lesson-8",
    lessonTitle: "NumPy Advanced Operations",
    content: "Broadcasting rules:\n1. Arrays are compared element-by-element\n2. Dimensions are compatible if equal or one of them is 1\n3. Arrays can be broadcast if all dimensions are compatible",
    timestamp: 850,
    createdAt: "2024-05-20T10:00:00Z",
    updatedAt: "2024-05-21T09:00:00Z",
  },
  {
    id: "note-3",
    userId: "user-learner-1",
    courseId: "course-6",
    courseTitle: "Zero Trust Network Architecture",
    lessonId: "lesson-5",
    lessonTitle: "Identity-Centric Security",
    content: "Zero Trust principles:\n- Never trust, always verify\n- Assume breach\n- Apply least privilege\n- Inspect and log all traffic",
    createdAt: "2024-05-15T16:00:00Z",
    updatedAt: "2024-05-15T16:00:00Z",
  },
];

export const MOCK_DOUBTS: Doubt[] = [
  {
    id: "doubt-1",
    userId: "user-learner-2",
    userName: "Sarah J.",
    courseId: "course-3",
    courseTitle: "Design Systems in React",
    lessonId: "lesson-20",
    lessonTitle: "useEffect and Side Effects",
    question: "How does the useEffect dependency array handle deep object comparisons?",
    description: "I notice that useEffect triggers even when the object reference is the same but contents might have changed. How do we handle this properly?",
    status: "pending",
    createdAt: "2024-05-28T10:15:00Z",
    updatedAt: "2024-05-28T10:15:00Z",
    upvotes: 12,
  },
  {
    id: "doubt-2",
    userId: "user-learner-3",
    userName: "Mike T.",
    courseId: "course-3",
    courseTitle: "Design Systems in React",
    lessonId: "lesson-5",
    lessonTitle: "Figma Component Basics",
    question: "I can't seem to get auto-layout to wrap properly on this card component.",
    description: "Following the video but the cards overflow instead of wrapping to a new row. Attached a screenshot of my Figma setup.",
    status: "pending",
    createdAt: "2024-05-28T09:00:00Z",
    updatedAt: "2024-05-28T09:00:00Z",
    upvotes: 5,
  },
  {
    id: "doubt-3",
    userId: "user-learner-1",
    userName: "Alex Johnson",
    courseId: "course-6",
    courseTitle: "Zero Trust Network Architecture",
    question: "Clarification needed on Docker volume persistence in module 4.2.",
    status: "pending",
    createdAt: "2024-05-25T12:00:00Z",
    updatedAt: "2024-05-25T12:00:00Z",
    upvotes: 8,
  },
  {
    id: "doubt-4",
    userId: "user-learner-4",
    userName: "Arjun Patel",
    courseId: "course-1",
    courseTitle: "Advanced Python for Data Science",
    question: "What is the best way to handle class imbalance in a classification problem?",
    status: "answered",
    answeredByName: "Dr. Ankit Sharma",
    answer: "Great question! There are several approaches: 1) Oversampling minority class with SMOTE, 2) Undersampling majority class, 3) Using class_weight='balanced' in sklearn models, 4) Using appropriate metrics like F1, ROC-AUC instead of accuracy.",
    answeredAt: "2024-05-24T16:00:00Z",
    createdAt: "2024-05-24T10:00:00Z",
    updatedAt: "2024-05-24T16:00:00Z",
    upvotes: 32,
  },
];

export const MOCK_CERTIFICATES: Certificate[] = [
  {
    id: "cert-1",
    userId: "user-learner-1",
    userName: "Alex Johnson",
    courseId: "course-old-1",
    courseTitle: "AWS Solutions Architect Associate",
    institutionId: "inst-1",
    institutionName: "TechGlobal Institute",
    issuedAt: "2023-09-15T00:00:00Z",
    verificationCode: "LX-CERT-2023-001-AWSSolArch",
    verificationUrl: "https://learniox.com/verify/LX-CERT-2023-001-AWSSolArch",
    grade: "Distinction",
  },
  {
    id: "cert-2",
    userId: "user-learner-1",
    userName: "Alex Johnson",
    courseId: "course-old-2",
    courseTitle: "React Advanced Patterns",
    institutionId: "inst-3",
    institutionName: "Design Institute",
    issuedAt: "2024-01-20T00:00:00Z",
    verificationCode: "LX-CERT-2024-002-ReactAdv",
    verificationUrl: "https://learniox.com/verify/LX-CERT-2024-002-ReactAdv",
    grade: "Merit",
  },
  {
    id: "cert-3",
    userId: "user-learner-1",
    userName: "Alex Johnson",
    courseId: "course-old-3",
    courseTitle: "Python for Data Analysis",
    institutionId: "inst-4",
    institutionName: "DataSys Academy",
    issuedAt: "2023-12-01T00:00:00Z",
    verificationCode: "LX-CERT-2023-003-PyData",
    verificationUrl: "https://learniox.com/verify/LX-CERT-2023-003-PyData",
  },
];

export const MOCK_USER_MEMBERSHIPS: MembershipSubscription[] = [
  {
    id: "sub-1",
    userId: "user-learner-1",
    institutionId: "inst-3",
    institutionName: "Design Institute",
    membershipId: "membership-2",
    membershipName: "Design Pro",
    price: 999,
    billingCycle: "monthly",
    status: "active",
    startedAt: "2024-03-01T00:00:00Z",
    renewsAt: "2024-06-01T00:00:00Z",
    paymentMethod: "UPI",
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "pay-1",
    userId: "user-learner-1",
    courseId: "course-1",
    institutionId: "inst-1",
    amount: 4999,
    currency: "INR",
    status: "success",
    method: "upi",
    gateway: "razorpay",
    gatewayOrderId: "order_NxKjGd8ABC",
    gatewayPaymentId: "pay_NxKjGd8XYZ",
    paidAt: "2024-03-01T10:00:00Z",
    createdAt: "2024-03-01T10:00:00Z",
    description: "Purchase: Advanced Python for Data Science",
  },
  {
    id: "pay-2",
    userId: "user-learner-1",
    institutionId: "inst-3",
    membershipId: "membership-2",
    amount: 999,
    currency: "INR",
    status: "success",
    method: "upi",
    gateway: "razorpay",
    paidAt: "2024-05-01T10:00:00Z",
    createdAt: "2024-05-01T10:00:00Z",
    description: "Renewal: Design Pro - Design Institute",
  },
];

export const MOCK_ASSIGNMENT_SUBMISSIONS: AssignmentSubmission[] = [
  {
    id: "sub-assign-1",
    assignmentId: "assign-1",
    userId: "user-learner-2",
    courseId: "course-3",
    submittedAt: "2024-05-27T14:00:00Z",
    content: "Built a responsive card component using design tokens...",
    status: "submitted",
    maxScore: 100,
  },
];
