import type { User, LearnerProfile, InstructorProfile } from "@/types/user";

export const MOCK_CURRENT_USER: LearnerProfile = {
  id: "user-learner-1",
  email: "alex@example.com",
  name: "Alex Johnson",
  avatar: undefined,
  bio: "Software engineer passionate about machine learning and system design.",
  role: "learner",
  status: "active",
  isEmailVerified: true,
  phone: "+91 98765 43210",
  location: "Bangalore, India",
  website: "https://alexj.dev",
  expertise: ["Python", "React", "System Design"],
  enrollmentCount: 12,
  completedCourseCount: 48,
  certificateCount: 3,
  watchTimeHours: 840,
  xpPoints: 12450,
  level: "advanced",
  createdAt: "2023-09-01T00:00:00Z",
  lastLoginAt: "2024-05-28T10:30:00Z",
};

export const MOCK_CURRENT_STUDIO_USER: User = {
  id: "user-owner-3",
  email: "ritu@designinstitute.in",
  name: "Ritu Kapoor",
  avatar: undefined,
  bio: "Lead UI Engineer and Educator. Founder of Design Institute.",
  role: "owner",
  status: "active",
  isEmailVerified: true,
  institutionId: "inst-3",
  createdAt: "2024-02-01T00:00:00Z",
  lastLoginAt: "2024-05-28T10:00:00Z",
};

export const MOCK_INSTRUCTORS: InstructorProfile[] = [
  {
    id: "user-instructor-1",
    email: "ankit@techglobal.edu.in",
    name: "Dr. Ankit Sharma",
    title: "Senior ML Engineer",
    bio: "10+ years in ML/AI. Former Google Brain researcher. Author of 3 ML books.",
    role: "instructor",
    status: "active",
    isEmailVerified: true,
    institutionIds: ["inst-1"],
    courseCount: 8,
    studentCount: 28500,
    rating: 4.9,
    reviewCount: 4200,
    expertise: ["Python", "Machine Learning", "Deep Learning", "MLOps"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "user-instructor-2",
    email: "priya@techglobal.edu.in",
    name: "Priya Mehta",
    title: "Principal Software Architect",
    bio: "15 years designing enterprise systems for Fortune 500 companies. AWS Solutions Architect Professional.",
    role: "instructor",
    status: "active",
    isEmailVerified: true,
    institutionIds: ["inst-1", "inst-2"],
    courseCount: 5,
    studentCount: 14200,
    rating: 4.8,
    reviewCount: 2100,
    expertise: ["System Design", "Microservices", "AWS", "Architecture"],
    createdAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "user-instructor-3",
    email: "ritu@designinstitute.in",
    name: "Ritu Kapoor",
    title: "Lead UI Engineer",
    bio: "Ex-Zomato, ex-Flipkart design lead. Now running Design Institute full-time.",
    role: "owner",
    status: "active",
    isEmailVerified: true,
    institutionIds: ["inst-3"],
    courseCount: 12,
    studentCount: 22100,
    rating: 4.8,
    reviewCount: 3200,
    expertise: ["UI Design", "Design Systems", "React", "Figma"],
    createdAt: "2024-02-01T00:00:00Z",
  },
];

export const MOCK_LEARNERS: User[] = [
  {
    id: "user-learner-2",
    email: "sarah.j@example.com",
    name: "Sarah J.",
    role: "learner",
    status: "active",
    isEmailVerified: true,
    createdAt: "2024-03-01T00:00:00Z",
    lastLoginAt: "2024-05-27T15:00:00Z",
  },
  {
    id: "user-learner-3",
    email: "mike.t@example.com",
    name: "Mike T.",
    role: "learner",
    status: "active",
    isEmailVerified: true,
    createdAt: "2024-04-01T00:00:00Z",
    lastLoginAt: "2024-05-26T12:00:00Z",
  },
  {
    id: "user-learner-4",
    email: "arjun.p@example.com",
    name: "Arjun Patel",
    role: "learner",
    status: "active",
    isEmailVerified: true,
    location: "Mumbai",
    createdAt: "2023-11-01T00:00:00Z",
    lastLoginAt: "2024-05-28T09:00:00Z",
  },
];
